### ISSUE TITLE
how to train

### ISSUE THREAD

**Issue by fzuqxt** [megvii-research/WACV2024-SAFA#1]
Hello author, I am very interested in your work, may I ask how to start training?

**Comment by hzwer** [comment]
We are cleaning up the code and the training loop is similar to videoINR and RIFE.

**Comment by fzuqxt** [comment]
ok,thanks

**Comment by fzuqxt** [comment]
Hello author, can you provide the training code

**Comment by hzwer** [comment]
hi @fzuqxt 
The code is uploaded. https://github.com/megvii-research/WACV2024-SAFA/blob/main/train.py and https://github.com/megvii-research/WACV2024-SAFA/blob/main/dataset.py

Not tested yet, I'll get around to it this week.
Sorry for the inconvenience caused to you.

**Comment by fzuqxt** [comment]
Thank you very much. Can the training code run normally now?

**Comment by hzwer** [comment]
Did you encounter any problems? The codes of training loop are mainly from https://github.com/megvii-research/ECCV2022-RIFE/tree/main. I think they should be OK.
