### ISSUE TITLE
Model seems to produce very over-sharpened results

### ISSUE THREAD

**Issue by KLC04** [megvii-research/WACV2024-SAFA#2]
The provided pre- train seems to have an issue of significantly over sharpening while not adding any usable detail. Is this a known issue in the works?

**Comment by hzwer** [comment]
We recently tried to study models for visual effects. Current experimental models do not perform well on videos that appear to be synthesized differently from the training data. We are improving data augmentation refer to [real-ESRGAN](https://github.com/xinntao/Real-ESRGAN).

**Comment by hzwer** [comment]
https://github.com/hzwer/Practical-RIFE/tree/main#video-enhancement

**Comment by KLC04** [comment]
Thanks for updating me! In my understanding this is for enhancement right, so no uspcaling and no interpolation?

**Comment by hzwer** [comment]
Yes, I hope to eliminate the influence of other factors and study the real degradation first.
