### ISSUE TITLE
Table 1中two-stage方法的训练集是什么呢？

### ISSUE THREAD

**Issue by DachunKai** [megvii-research/WACV2024-SAFA#4]
请问table1中的VFI和VSR方法的训练集是Adobe240吗？都是retrain过来的吗？还是用的原论文作者公开的预训练模型呢？

**Comment by hzwer** [comment]
VFI 是 Adobe240 训练的，具体可以参考 https://arxiv.org/pdf/2206.04647.pdf 的附录
SR 是预训练模型

**Comment by DachunKai** [comment]
好的，谢谢！
