### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by yeluohuazhifou** [megvii-research/WACV2024-SAFA#6]
class RecurrentBlock(nn.Module):
    def __init__(self, c, dilation=1, depth=6):
        super(RecurrentBlock, self).__init__()
        self.conv_stem = conv(3*c+6+1, c, 3, 1, 1, groups=1)
        self.conv_backbone = torch.nn.ModuleList([])
        self.depth = depth
        for i in range(depth):
            self.conv_backbone.append(Resblock(c, dilation))
        
    def forward(self, x, i0, i1, flow, timestep, convflow, getscale):
        flow_down = F.interpolate(flow, scale_factor=0.5, mode="bilinear")
        i0 = warp(i0, flow_down[:, :2] * 0.5)
        i1 = warp(i1, flow_down[:, 2:4] * 0.5)
        x = torch.cat((x, flow_down, i0, i1, timestep), 1) # [1,80,368,640], [1,6,368,640], [1,80,368,640], [1,80,368,640], [1,1,368,640]
        # print(x.shape)
        # exit(0)
        scale = RoundSTE.apply(getscale(x)).unsqueeze(2).unsqueeze(3) # [1,2,1,1]
        # print(scale)
        # exit(0)
        feat = 0
        if scale.shape[0] != 1 or (scale[:, 0:1].mean() >= 0.5 and scale[:, 1:2].mean() >= 0.5):
            x0 = self.conv_stem(x)
            for i in range(self.depth):
                x0 = self.conv_backbone[i](x0)
            feat = feat + x0 * scale[:, 0:1] * scale[:, 1:2] 

        if scale.shape[0] != 1 or (scale[:, 0:1].mean() < 0.5 and scale[:, 1:2].mean() >= 0.5):
            x1 = self.conv_stem(F.interpolate(x, scale_factor=0.5, mode="bilinear"))
            for i in range(self.depth):
                x1 = self.conv_backbone[i](x1)
            feat = feat + F.interpolate(x1, scale_factor=2.0, mode="bilinear") * (1 - scale[:, 0:1]) * scale[:, 1:2]

        if scale.shape[0] != 1 or scale[:, 1:2].mean() < 0.5:
            x2 = self.conv_stem(F.interpolate(x, scale_factor=0.25, mode="bilinear")) # [1,80,92,160]
            # print(x2.shape)
            # exit(0)
            for i in range(self.depth):
                x2 = self.conv_backbone[i](x2)
            feat = feat + F.interpolate(x2, scale_factor=4.0, mode="bilinear") * (1 - scale[:, 1:2])
        return feat, convflow(feat) + flow, i0, i1, scale
feat应该在for循环里吧，放在外面看起来有点问题；论文暂时还没看，直接看的代码

**Comment by hzwer** [comment]
我想实现的是，x0, x1, x2 会经历若干个 resblock，然后加到 feat 上
feat 这里放在 for 里面的话，相当于把每一 resblock 的结果都加给 feat
