### ISSUE TITLE
Video superscoring is slow?

### ISSUE THREAD

**Issue by lgthappy** [megvii-research/WACV2024-SAFA#9]
Hello, according to your project after downloading the model and running inference_video_enhance.py --video movie_540p.mp4 --fp16,but the actual look is very slow, so this is definitely not real time, would like to ask is it normal to be so slow? Or do you have some data on inference speed?

**Comment by hzwer** [comment]
![image](https://github.com/user-attachments/assets/85f2e812-09a2-4dd9-aa87-606583cf5d8f)
It is indeed not real-time, but it won't be excessively slow either. Are you sure you are using GPU inference?

**Comment by lgthappy** [comment]
> ![image](https://private-user-images.githubusercontent.com/10103856/398505502-85f2e812-09a2-4dd9-aa87-606583cf5d8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxODQ5MjksIm5iZiI6MTczNTE4NDYyOSwicGF0aCI6Ii8xMDEwMzg1Ni8zOTg1MDU1MDItODVmMmU4MTItMDlhMi00ZGQ5LWFhODctNjA2NTgzY2Y1ZDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDAzNDM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0ZGQ4MzQ3NDdiYzg5M2IwNDhlNDQxOTJiMTU3MDg2NDYwOWZlMTNkMWUxYzNiMmIxYzNmYWIxNTA4NTNkMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7jFM_yBdshYtj5c28zsel0DREamQ6NvH7gKO30zqZNA) It is indeed not real-time, but it won't be excessively slow either. Are you sure you are using GPU inference?

Hi ，Het gebruikt GPU-inferentie, maar 540p video lijkt niet snel te zijn, dit is de inferentiesnelheid voor video met een resolutie van 540p:
540p.mp4, 19536,0 frames in totaal, 29,97002997002997FPS tot 59,94005994005994FPS.
De audio wordt samengevoegd na het interpolatieproces
100%|█████████▉| 19535/19536.0 [17:10<00:00, 18.95it/s]

**Comment by hzwer** [comment]
Hello, considering the overhead of model input and output, the current speed is approximately like this.
